# see: https://github.com/thomaseizinger/github-action-gitflow-release-workflow

name: "2.1 - Create Tag From Merge"

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  gather_versions:
    name: Publish new release
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.gather_version_pr.outputs.release_version }}

    # only merged pull requests that begin with 'release/' or 'hotfix/' must trigger this job
    if: github.event.pull_request.merged == true &&
      (startsWith(github.event.pull_request.head.ref, 'release/') || startsWith(github.event.pull_request.head.ref, 'hotfix/'))

    steps:
      - id: gather_version_pr
        name: Extract version from branch name (for release branches)
        if: startsWith(github.event.pull_request.head.ref, 'release/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release/}

          echo "release_version=$VERSION" >> $GITHUB_OUTPUT

      - id: gather_version_hotfix
        name: Extract version from branch name (for hotfix branches)
        if: startsWith(github.event.pull_request.head.ref, 'hotfix/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#hotfix/}

          echo "release_version=$VERSION" >> $GITHUB_OUTPUT
          
  create_tag:
    runs-on: ubuntu-latest
    needs: gather_versions
    steps:
      - uses: Alex-Chopard/gh-release/.github/workflows/create_tag.yml@main
        with:
          release_version: ${{ needs.gather_versions.outputs.release_version }}
          pr_number: ${{ github.event.number }}

          
          
          
