# see: https://github.com/thomaseizinger/github-action-gitflow-release-workflow

name: "Create Release Tag"

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release:
    name: Publish new release
    runs-on: ubuntu-latest
    # only merged pull requests that begin with 'release/' or 'hotfix/' must trigger this job
    if: github.event.pull_request.merged == true &&
      (startsWith(github.event.pull_request.head.ref, 'release/') || startsWith(github.event.pull_request.head.ref, 'hotfix/'))

    steps:
      - name: Extract version from branch name (for release branches)
        if: startsWith(github.event.pull_request.head.ref, 'release/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release/}

          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Extract version from branch name (for hotfix branches)
        if: startsWith(github.event.pull_request.head.ref, 'hotfix/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#hotfix/}

          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
          
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Initialize mandatory git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
      - name: Create Tag
        run: |
          git tag -a v${{ env.RELEASE_VERSION }} -m "v${{ env.RELEASE_VERSION }}\n\t See: #${{ github.event.number }} for more details."
          git push --tags
          echo ${{ github.event }}
      
          
          
          
          
          
